#spring.profiles.active=prod
server.port=18880
spring.datasource.username=chengde
spring.datasource.password=Cd22sH1@1z
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/elevator?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
elevator.root.path=/app/elevator
elevator.screenshot.path=/screenshot/
elevator.report.path=/report/
elevator.export.path=/export/
elevator.maintenance.path=/maintenance/