#spring.profiles.active=test
server.port=43658
spring.datasource.url=jdbc:postgresql://172.31.3.243:5432/gov_duban_dev3
elevator.root.path=/app/elevator
elevator.screenshot.path=/screenshot/
elevator.report.path=/report/
elevator.export.path=/export/
elevator.maintenance.path=/maintenance/